version: '3.3'
services:
  gitea:
    image: gitea/gitea
    environment:
    - USER_UID=1000
    - USER_GID=1000
    volumes:
    - data:/data
    networks:
    - wappsfrontend
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    - traefik.port=3000
    restart: always
volumes:
  data:
networks:
  wappsfrontend:
    external: true
