version: '3.3'
services:
  postgres:
    image: postgres
    environment:
    - POSTGRES_USER=${DB_USERNAME}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
    - postgres:/var/lib/postgresql/data
    networks:
    - wappsbackend
    restart: always
  cachet:
    image: cachethq/docker
    env_file: .env
    environment:
    - DB_DRIVER=pgsql
    - DB_HOST=${COMPOSE_PROJECT_NAME}_postgres_1
    - DB_PORT=5432
    - APP_LOG=errorlog
    - DEBUG=false
    networks:
    - wappsfrontend
    - wappsbackend
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    - traefik.docker.network=wappsfrontend
    - traefik.docker.port=8000
    restart: always
    depends_on:
    - postgres
volumes:
    postgres:
networks:
  wappsfrontend:
    external: true
  wappsbackend:
    external: true
