version: "2"
networks:
  wapps:
    external:
      name: "wapps"
services:
  mysql:
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    image: "mysql:5"
    networks:
      - "wapps"
    restart: "always"
    volumes:
      - "mysql:/var/lib/mysql"
  matomo:
    environment:
      - "MATOMO_DATABASE_HOST=mysql"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    image: "matomo"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.matomo-http.entrypoints=http"
      - "traefik.http.routers.matomo-http.middlewares=wapps"
      - "traefik.http.routers.matomo-http.rule=Host(`${HOST}`)"
      - "traefik.http.routers.matomo-https.entrypoints=https"
      - "traefik.http.routers.matomo-https.rule=Host(`${HOST}`)"
      - "traefik.http.routers.matomo-https.tls.certResolver=wapps"
      - "traefik.http.services.matomo.loadbalancer.server.port=80"
    networks:
      - "wapps"
    restart: "always"
    volumes:
      - "./config:/var/www/html/config"
volumes:
  mysql:
    driver: local
