version: '3.3'
services:
  pihole:
    image: pihole/pihole
    env_file: .env
    volumes:
    - pihole:/etc/pihole/
    - dnsmasq:/etc/dnsmasq.d/
    - ./hosts:/etc/hosts
    networks:
    - wappsfrontend
    ports:
    - ${ServerIP}:53:53/tcp
    - ${ServerIP}:53:53/udp
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:${TRAEFIK_HOST};AddPrefix:/admin
    - traefik.port=80
    restart: always
volumes:
  pihole:
  dnsmasq:
networks:
  wappsfrontend:
    external: true
