version: '3.3'
services:
  metabase:
    image: metabase/metabase
    networks:
    - wappsfrontend
    - wappsbackend
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    - traefik.frontend.entryPoints=https-mgmt
    - traefik.docker.network=wappsfrontend
    restart: always
networks:
  wappsfrontend:
    external: true
  wappsbackend:
    external: true
