version: "2"
networks:
  wapps:
    external:
      name: "wapps"
services:
  pihole:
    image: "pihole/pihole"
    volumes:
      - "dnsmasq:/etc/dnsmasq.d/"
      - "hosts:/etc/hosts"
      - "pihole:/etc/pihole/"
    networks:
      - "wapps"
    ports:
      - "${IP}:53:53/tcp"
      - "${IP}:53:53/udp"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.middlewares.pihole.addprefix.prefix=/admin"
      - "traefik.http.routers.pihole.entrypoints=http,https"
      - "traefik.http.routers.pihole.middlewares=pihole,wapps"
      - "traefik.http.routers.pihole.rule=Host(`${HOST}`)"
      - "traefik.http.routers.pihole.tls.certResolver=wapps"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    restart: "always"
volumes:
  dnsmasq:
  hosts:
  pihole:
