version: "2"
networks:
  wapps:
    external:
      name: "wapps"
services:
  pihole:
    cap_add:
      - NET_ADMIN
    environment:
      - "DNS1=${DNS1}"
      - "DNS2=${DNS2}"
      - "PASSWORD=${PASSWORD}"
      - "TZ=${TZ}"
    image: "pihole/pihole"
    networks:
      - "wapps"
    ports:
      - "${IP}:53:53/tcp"
      - "${IP}:53:53/udp"
      - "${IP}:67:67/udp"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.middlewares.pihole.addprefix.prefix=/admin"
      - "traefik.http.routers.pihole.entrypoints=http"
      - "traefik.http.routers.pihole.middlewares=pihole,wapps"
      - "traefik.http.routers.pihole.rule=Host(`${HOST}`)"
      - "traefik.http.routers.pihole-https.entrypoints=https"
      - "traefik.http.routers.pihole-https.middlewares=pihole"
      - "traefik.http.routers.pihole-https.rule=Host(`${HOST}`)"
      - "traefik.http.routers.pihole-https.tls.certResolver=wapps"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    restart: "always"
    volumes:
      - "dnsmasq:/etc/dnsmasq.d/"
      - "pihole:/etc/pihole/"
volumes:
  dnsmasq:
    driver: local
  pihole:
    driver: local
