version: '3.3'
services:
  bazarr:
    image: linuxserver/bazarr
    volumes:
    - config:/config
    - /etc/localtime:/etc/localtime:ro
    - ${SERIES_DIR}:/tv
    - ${MOVIES_DIR}:/movies
    networks:
    - wapps_frontend
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    restart: always
volumes:
  config:
networks:
  wapps_frontend:
    external: true
