version: "2"
networks:
  wapps:
    external:
      name: "wapps"
services:
  prowlarr:
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      - "UMASK_SET=${UMASK_SET}"
    image: "linuxserver/prowlarr"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.prowlarr-http.entrypoints=http"
      - "traefik.http.routers.prowlarr-http.middlewares=wapps"
      - "traefik.http.routers.prowlarr-http.rule=Host(`${HOST}`)"
      - "traefik.http.routers.prowlarr-https.entrypoints=https"
      - "traefik.http.routers.prowlarr-https.middlewares=sso"
      - "traefik.http.routers.prowlarr-https.rule=Host(`${HOST}`)"
      - "traefik.http.routers.prowlarr-https.tls.certResolver=wapps"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    networks:
      - "wapps"
    restart: "always"
    volumes:
      - "config:/config"
volumes:
  config:
    driver: "local"
