version: "2"
networks:
  wapps:
    external:
      name: "wapps"
services:
  mysql:
    environment:
      - "MYSQL_DATABASE:${MYSQL_DATABASE}"
      - "MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER:${MYSQL_USER}"
      - "MYSQL_PASSWORD:${MYSQL_PASSWORD}"
    image: "mysql"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - "wapps"
    restart: "always"
    volumes:
      - "mysql:/var/lib/mysql"
  bookstack:
    environment:
      - "APP_URL=https://${HOST}"
      - "DB_HOST=${COMPOSE_PROJECT_NAME}_mysql_1:3306"
      - "DB_DATABASE=${MYSQL_DATABASE}"
      - "DB_USERNAME=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
    image: "solidnerd/bookstack"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.bookstack-http.entrypoints=http"
      - "traefik.http.routers.bookstack-http.middlewares=wapps"
      - "traefik.http.routers.bookstack-http.rule=Host(`${HOST}`)"
      - "traefik.http.routers.bookstack-https.entrypoints=https"
      - "traefik.http.routers.bookstack-https.rule=Host(`${HOST}`)"
      - "traefik.http.routers.bookstack-https.tls.certResolver=wapps"
      - "traefik.http.services.bookstack.loadbalancer.server.port=80"
    networks:
      - "wapps"
    restart: "always"
    volumes:
      - "uploads:/var/www/bookstack/public/uploads"
      - "storage:/var/www/bookstack/public/storage"
volumes:
  mysql:
    driver: local
  uploads:
    driver: local
  storage:
    driver: local
