version: '3.3'
services:
  mysql:
    image: mysql:5.7.22
    volumes:
    - mysql:/var/lib/mysql
    networks:
    - wappsbackend
    env_file: .env
    restart: always
  matomo:
    image: matomo
    volumes:
    - ./config:/var/www/html/config
    - ./misc:/var/www/html/misc
    networks:
    - wappsfrontend
    - wappsbackend
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    - traefik.docker.network=wappsfrontend
    restart: always
    links:
    - mysql
volumes:
  mysql:
networks:
  wappsfrontend:
    external: true
  wappsbackend:
    external: true
