version: '3.3'
services:
  mysql:
    image: mysql
    volumes:
    - mysql:/var/lib/mysql
    networks:
    - wapps-backends
    env_file: .env
    restart: always
  matomo:
    image: matomo
    networks:
    - wapps-frontends
    - wapps-backends
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    - traefik.docker.network=wapps-frontends
    restart: always
volumes:
  mysql:
networks:
  wapps-frontends:
    external: true
  wapps-backends:
    external: true
