version: '3.3'
services:
  mysql:
    image: mysql
    volumes:
    - mysql:/var/lib/mysql
    networks:
    - wappsbackend
    env_file: .env
    restart: always
  matomo:
    image: matomo
    volumes:
    - html:/var/www/html
    - ./misc:/usr/src/piwik/misc
    networks:
    - wappsfrontend
    - wappsbackend
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    - traefik.docker.network=wappsfrontend
    restart: always
volumes:
  mysql:
  html:
networks:
  wappsfrontend:
    external: true
  wappsbackend:
    external: true
