version: '3.3'
services:
  mysql:
    image: mysql
    volumes:
    - /opt/trck:/var/lib/mysql
    env_file: .env
    restart: always
  matomo:
    image: piwik
    networks:
      - default
      - prxy_default
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${TRAEFIK_HOST}
      - traefik.docker.network=prxy_default
    restart: always
networks:
  prxy_default:
    external: true
