version: '3.3'
services:
  portainer:
    image: portainer/portainer
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - data:/data
    networks:
    - wapps_frontend
    labels:
    - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    - traefik.frontend.entryPoints=https-mgmt
    - traefik.enable=true
    restart: always
  watchtower:
    image: containrrr/watchtower
    networks:
    - wapps_frontend
    env_file: .env
    environment:
    - WATCHTOWER_CLEANUP=true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - wapps_backend
    restart: always
volumes:
  data:
networks:
  wapps_backend:
    external: true
  wapps_frontend:
    external: true
