version: "2"
networks:
  wapps:
    external:
      name: "wapps"
services:
  heimdall:
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: linuxserver/heimdall
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.heimdall-http.entrypoints=http"
      - "traefik.http.routers.heimdall-http.middlewares=wapps-mgmt"
      - "traefik.http.routers.heimdall-http.rule=Host(`${HOST}`)"
      - "traefik.http.routers.heimdall-https.entrypoints=https"
      - "traefik.http.routers.heimdall-https.middlewares=wapps-mgmt"
      - "traefik.http.routers.heimdall-https.rule=Host(`${HOST}`)"
      - "traefik.http.routers.heimdall-https.tls.certResolver=wapps"
      - "traefik.http.routers.heimdall-https-mgmt.entrypoints=https-mgmt"
      - "traefik.http.routers.heimdall-https-mgmt.middlewares=sso"
      - "traefik.http.routers.heimdall-https-mgmt.rule=Host(`${HOST}`)"
      - "traefik.http.routers.heimdall-https-mgmt.tls.certResolver=wapps"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
    networks:
      - "wapps"
    restart: "always"
    volumes:
      - config:/config
volumes:
  config:
    driver: "local"
