version: '3.3'
services:
  postgres:
    image: postgres
    volumes:
    - postgres:/var/lib/postgresql/data
    networks:
    - wappsbackend
    restart: always
  cachet:
    image: cachethq/docker
    env_file:
    environment:
    - DB_DRIVER=pgsql
    - DB_HOST=${COMPOSE_PROJECT_NAME}_postgres_1
    - DB_PORT=5432
    - APP_KEY=${APP_KEY:-null}
    - APP_LOG=errorlog
    - DEBUG=false
    networks:
    - wappsfrontend
    - wappsbackend
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    - traefik.docker.network=wappsfrontend
    restart: always
    depends_on:
    - postgres
