version: '3.3'
services:
  plex:
    image: linuxserver/plex
    environment:
    - VERSION=docker
    volumes:
    - /mnt/FILE1-FNS/Videos/Plex:/config
    - /mnt/FILE1-FNS/Videos:/data
    networks:
    - wappsfrontend
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    restart: always
networks:
  wappsfrontend:
    external: true
