version: "2"
networks:
  wapps:
    external:
      name: "wapps"
services:
  minio:
    command: "server /data"
    environment:
      - "MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}"
      - "MINIO_SECRET_KEY=${MINIO_SECRET_KEY}"
    image: "minio/minio"
    networks:
      - "wapps"
    restart: "always"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.minio-http.entrypoints=http"
      - "traefik.http.routers.minio-http.middlewares=wapps"
      - "traefik.http.routers.minio-http.rule=Host(`${HOST}`)"
      - "traefik.http.routers.minio-https.entrypoints=https"
      - "traefik.http.routers.minio-https.rule=Host(`${HOST}`)"
      - "traefik.http.routers.minio-https.tls.certResolver=wapps"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
    volumes:
    - "${ROOT}:/data"
