version: "2"
networks:
  wapps:
    external:
      name: "wapps"
services:
  mysql-ba535ef5a9f7b8bc875812bb081286bb:
    build: .
    environment:
      - "MYSQL_DATABASE:${MYSQL_DATABASE}"
      - "MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER:${MYSQL_USER}"
      - "MYSQL_PASSWORD:${MYSQL_PASSWORD}"
    networks:
      - "wapps"
    volumes:
      - "mysql:/var/lib/mysql"
    restart: "always"
  guacd-ba535ef5a9f7b8bc875812bb081286bb:
    image: "guacamole/guacd:1.0.0"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - "wapps"
    restart: always
  guacamole:
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_HOSTNAME=mysql-ba535ef5a9f7b8bc875812bb081286bb"
      - "GUACD_HOSTNAME=guacd-ba535ef5a9f7b8bc875812bb081286bb"
    image: "guacamole/guacamole:1.0.0"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.middlewares.guacamole.addprefix.prefix=/guacamole"
      - "traefik.http.routers.guacamole-http.entrypoints=http"
      - "traefik.http.routers.guacamole-http.middlewares=guacamole,wapps"
      - "traefik.http.routers.guacamole-http.rule=Host(`${HOST}`)"
      - "traefik.http.routers.guacamole-https.entrypoints=https"
      - "traefik.http.routers.guacamole-https.middlewares=guacamole"
      - "traefik.http.routers.guacamole-https.rule=Host(`${HOST}`)"
      - "traefik.http.routers.guacamole-https.tls.certResolver=wapps"
      - "traefik.http.services.guacamole.loadbalancer.server.port=8000"
    networks:
      - "wapps"
    restart: "always"
volumes:
  mysql:
    driver: local
