version: '3.3'
services:
  mysql:
    image: mysql
    env_file: .env
    volumes:
    - mysql:/var/lib/mysql
    networks:
    - wappsbackend
  wallabag:
    image: wallabag/wallabag
    env_file: .env
    environment:
    - SYMFONY__ENV__DOMAIN_NAME=https://${TRAEFIK_HOST}
    volumes:
    - images:/var/www/wallabag/web/assets/images
    networks:
    - wappsfrontend
    - wappsbackend
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    - traefik.docker.network=wappsfrontend
volumes:
  mysql:
  images:
networks:
  wappsfrontend:
    external: true
  wappsbackend:
    external: true
