version: '3.3'
services:
  traefik:
    image: traefik
    ports:
    - 80:80
    - 443:443
    - 8080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik.toml:/traefik.toml
    - ./tls.pem:/tls.pem
    - ./tls.key:/tls.key
    restart: always
