version: '3.3'
services:
  traefik:
    image: traefik
    networks:
    - wappsfront
    ports:
    - 80:80
    - 443:443
    - 4443:4443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik.toml:/traefik.toml
    - ./tls.pem:/tls.pem
    - ./tls.key:/tls.key
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    - traefik.frontend.entryPoints=https-mgmt
    - traefik.port=8080
    restart: always
networks:
  wappsfront:
    external: true
