version: "2"
networks:
  wapps:
    external: true
services:
  alltube:
    image: "rudloff/alltube"
    labels:
      - "traefik.http.routers.alltube.entrypoints=http,https,https-mgmt"
      - "traefik.http.routers.alltube.middlewares=wapps-mgmt"
      - "traefik.http.routers.alltube.rule=Host(`${HOST}`)"
      - "traefik.http.routers.alltube.tls.certResolver=wapps"
      - "traefik.http.services.alltube.loadbalancer.server.port=80"
    networks:
    - "wapps"
    restart: "always"
