version: "2"
networks:
  wapps:
    external:
      name: "wapps"
services:
  alltube:
    image: "rudloff/alltube"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.alltube-http.entrypoints=http"
      - "traefik.http.routers.alltube-http.middlewares=wapps-mgmt"
      - "traefik.http.routers.alltube-http.rule=Host(`${HOST}`)"
      - "traefik.http.routers.alltube-https.entrypoints=https"
      - "traefik.http.routers.alltube-https.middlewares=wapps-mgmt"
      - "traefik.http.routers.alltube-https.rule=Host(`${HOST}`)"
      - "traefik.http.routers.alltube-https.tls.certResolver=wapps"
      - "traefik.http.routers.alltube-https-mgmt.entrypoints=https-mgmt"
      - "traefik.http.routers.alltube-https-mgmt.middlewares=wapps-mgmt"
      - "traefik.http.routers.alltube-https-mgmt.rule=Host(`${HOST}`)"
      - "traefik.http.routers.alltube-https-mgmt.tls.certResolver=wapps"
      - "traefik.http.services.alltube.loadbalancer.server.port=80"
    networks:
      - "wapps"
    restart: "always"
