version: '3.3'
services:
  mysql:
    image: mysql:5.7.22
    env_file: .env
    volumes:
    - mysql:/var/lib/mysql
    networks:
    - wappsbackend
    restart: always
  phpipam:
    image: pierrecdn/phpipam
    env_file: .env
    environment:
    - MYSQL_ENV_MYSQL_HOST=${COMPOSE_PROJECT_NAME}_mysql_1
    networks:
    - wappsfrontend
    - wappsbackend
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    - traefik.docker.network=wappsfrontend
    restart: always
volumes:
  mysql:
networks:
  wappsfrontend:
    external: true
  wappsbackend:
    external: true
