version: '3.3'
services:
  rainloop:
    image: hardware/rainloop
    volumes:
    - data:/rainloop/data
    networks:
    - wapps_frontend
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    restart: always
volumes:
  data:
networks:
  wapps_frontend:
    external: true
