version: "2"
networks:
  wapps:
    external:
      name: "wapps"
services:
  radarr:
    image: "linuxserver/radarr"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.radarr.entrypoints=http,https"
      - "traefik.http.routers.radarr.middlewares=wapps"
      - "traefik.http.routers.radarr.rule=Host(`${HOST}`)"
      - "traefik.http.routers.radarr.tls.certResolver=wapps"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    networks:
    - "wapps"
    restart: "always"
    volumes:
    - "config:/config"
    - "/etc/localtime:/etc/localtime:ro"
    - "${MOVIES_ROOT}:/movies"
    - "${DOWNLOADS_ROOT}:${DOWNLOADS_ROOT}"
volumes:
  config:
