version: "2"
networks:
  wapps:
    external:
      name: "wapps"
services:
  mysql-1fece0cb254f1f45891bc9ee9fed72a9:
    environment:
      - "APP_KEY=${APP_KEY}"
      - "MYSQL_DATABASE=monica"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    image: "mysql:5"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - "wapps"
    restart: "always"
    volumes:
      - "mysql:/var/lib/mysql"
  monica:
    environment:
      - "DB_HOST=mysql-1fece0cb254f1f45891bc9ee9fed72a9"
      - "DB_USERNAME=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
    image: "monica"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.monica-http.entrypoints=http"
      - "traefik.http.routers.monica-http.middlewares=wapps"
      - "traefik.http.routers.monica-http.rule=Host(`${HOST}`)"
      - "traefik.http.routers.monica-https.entrypoints=https"
      - "traefik.http.routers.monica-https.rule=Host(`${HOST}`)"
      - "traefik.http.routers.monica-https.tls.certResolver=wapps"
      - "traefik.http.services.monica.loadbalancer.server.port=80"
    networks:
      - "wapps"
    restart: "always"
    volumes:
      - "storage:/var/www/html/storage"
volumes:
  mysql:
    driver: "local"
  storage:
    driver: "local"
