version: '3.3'
services:
  postgres:
    image: postgres
    volumes:
    - data:/var/lib/postgresql/data
    networks:
    - wappsbackend
    restart: always
  confluence:
    image: atlassian/confluence-server
    volumes:
    - confluence:/var/atlassian/application-data/confluence
    env_file: .env
    environment:
    - CATALINA_CONNECTOR_PROXYNAME=${TRAEFIK_HOST}
    - CATALINA_CONNECTOR_PROXYPORT=443
    - CATALINA_CONNECTOR_SCHEME=https
    - CATALINA_CONNECTOR_SECURE=true
    networks:
    - wappsfrontend
    - wappsbackend
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:${TRAEFIK_HOST}
    - traefik.docker.network=wappsfrontend
    - traefik.port=8090
    restart: always
    depends_on:
    - postgres
volumes:
  data:
  confluence:
networks:
  wappsfrontend:
    external: true
  wappsbackend:
    external: true
