version: "2"
networks:
  wapps:
    external:
      name: "wapps"
services:
  caddy:
    image: "abiosoft/caddy"
    networks:
      - "wapps"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.caddy-http.entrypoints=http"
      - "traefik.http.routers.caddy-http.middlewares=wapps"
      - "traefik.http.routers.caddy-http.rule=Host(`${HOST}`)"
      - "traefik.http.routers.caddy-https.entrypoints=https"
      - "traefik.http.routers.caddy-https.rule=Host(`${HOST}`)"
      - "traefik.http.routers.caddy-https.tls.certResolver=wapps"
      - "traefik.http.services.caddy.loadbalancer.server.port=80"
    restart: "always"
    volumes:
      - "${CONFIG}/Caddyfile:/etc/Caddyfile"
      - "${ROOT}:/var/www/html"
