version: "2"
networks:
  wapps:
    external:
      name: "wapps"
services:
  directus:
    environment:
      - "KEY=${DIRECTUS_KEY}"
      - "SECRET=${DIRECTUS_SECRET}"
      - "WEBSOCKETS_ENABLED=true"
      - "ADMIN_EMAIL=${DIRECTUS_EMAIL}"
      - "ADMIN_PASSWORD=${DIRECTUS_PASSWORD}"
      - "PUBLIC_URL=${HOST}"
      - "DB_CLIENT=sqlite3"
      - "DB_FILENAME=/directus/database/data.db"
    image: "directus/directus"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.strapi-http.entrypoints=http"
      - "traefik.http.routers.strapi-http.middlewares=wapps"
      - "traefik.http.routers.strapi-http.rule=Host(`${HOST}`)"
      - "traefik.http.routers.strapi-https.entrypoints=https"
      - "traefik.http.routers.strapi-https.rule=Host(`${HOST}`)"
      - "traefik.http.routers.strapi-https.tls.certResolver=wapps"
      - "traefik.http.services.strapi.loadbalancer.server.port=8055"
    networks:
      - "wapps"
    restart: "always"
    volumes:
      - "${DIRECTUS_UPLOADS_DIR}:/directus/uploads"
      - "${DIRECTUS_EXTENSIONS_DIR}:/directus/extensions"
      - "${DIRECTUS_DATABASE_DIR}:/directus/database"
